// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icthxbzcnitmgijkoaga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljdGh4Ynpjbml0bWdpamtvYWdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NjA2NDQsImV4cCI6MjA3MjMzNjY0NH0.RkQ2aXOzuXFTw1yaqB-drh5y-obV8l4ClufGxuUiHug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});